# Generated by Django 3.0.4 on 2021-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
