# Generated by Django 3.0.4 on 2021-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_block_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('followingusername', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('notification', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Addfriendnew',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
